######################################################################
#
# File name : tb_ip_2port_ram_wave.do
# Created on: Fri Mar 31 09:41:32 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
