webtalk_init -webtalk_dir E:/FPGA/z2/ip_2port_ram/prj/ip_2port_ram.sim/sim_1/behav/xsim/xsim.dir/tb_ip_2port_ram_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May  9 11:37:41 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "360028fb-f7c0-42cf-b120-8e20f1ca18f7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5f1b567e34ed4ae28a2af396f9499dbe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "37" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 3900X 12-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "21084_KB" -context "xsim\\usage"
webtalk_transmit -clientid 76426299 -regid "" -xml E:/FPGA/z2/ip_2port_ram/prj/ip_2port_ram.sim/sim_1/behav/xsim/xsim.dir/tb_ip_2port_ram_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/FPGA/z2/ip_2port_ram/prj/ip_2port_ram.sim/sim_1/behav/xsim/xsim.dir/tb_ip_2port_ram_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/FPGA/z2/ip_2port_ram/prj/ip_2port_ram.sim/sim_1/behav/xsim/xsim.dir/tb_ip_2port_ram_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
